export const GET_TOTAL_DATA = 'GET_TOTAL_DATA';
export const GET_CURRENT_PAGE_DATA = 'GET_CURRENT_PAGE_DATA';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const SELECT_CHANGE = 'SELECT_CHANGE';
export const SEND_SELECTED_ID = 'SEND_SELECTED_ID';